/*
 * DlgInventario.java
 * Creada el 27 de octubre del 2021 18:11 PM 
 */
package interfazUsuario;

import java.awt.Dimension;
import java.awt.Point;
import objetosNegocio.VideojuegoED;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import objetosNegocio.Videojuego;
import objetosServicio.Fecha;
import validores.Validadores;

/**
 * Cuadro de dialogo de inventario.
 * @author josej
 */
public class DlgInventario extends javax.swing.JDialog {

    /**
     * Creates new form DlgInventario
     *
     * @param parent Frame
     * @param titulo Titulo del frame
     * @param modal Modal
     * @param videojuegoED VideojuegoED
     * @param listaVideojuegos Lista de videojuegos
     * @param operacion Operacion a realizar
     * @param respuesta Respuesta
     */
    public DlgInventario(java.awt.Frame parent, String titulo, boolean modal, VideojuegoED videojuegoED, DefaultComboBoxModel listaVideojuegos, int operacion, StringBuffer respuesta) {
        super(parent, titulo, modal);
        this.videojuegoED = videojuegoED;
        this.listaVideojuegos = listaVideojuegos;
        this.operacion = operacion;
        this.respuesta = respuesta;
        initComponents();
        if (operacion == ConstantesGUI.AGREGAR) {
            botonAceptar.setText("Inventariar");
        } else if (operacion == ConstantesGUI.ELIMINAR) {
            botonAceptar.setText("Eliminar");
            botonRestaurar.setEnabled(false);
        }
        respuesta.append(ConstantesGUI.CANCELAR);
        centraCuadroDialogo(parent);
        setVisible(true);
    }

    /**
     * Metodo que centra el cuadro de dialogo
     *
     * @param parent Frame
     */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();

        Dimension dlgSize = getPreferredSize();

        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x,
                (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        botonRestaurar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTextoCantidad = new javax.swing.JTextField();
        cajaCombinadaVideojuegos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cantidadActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonRestaurar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonRestaurar.setText("Restaurar");
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cantidad;");

        campoTextoCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        campoTextoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCantidadActionPerformed(evt);
            }
        });

        cajaCombinadaVideojuegos.setModel(listaVideojuegos);
        cajaCombinadaVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCombinadaVideojuegosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Videojuegos;");

        cantidadActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(botonAceptar)
                .addGap(87, 87, 87)
                .addComponent(botonRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(cantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaCombinadaVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(cantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaCombinadaVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar)
                    .addComponent(botonRestaurar))
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
    * Evento que valida la cantidad a ingresar en el cuadro de dialog.
    * @param evt Evento del tipo action
    */
    private void campoTextoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCantidadActionPerformed
        String cantidad = campoTextoCantidad.getText();
        String msjError = "";
        if (validadores.cadenaVacia(cantidad)) {
            msjError = "Faltó la cantidad";
        } else if (!validadores.validaEntero(cantidad)) {
            msjError = "Solo digitos enteros";
        }
        if (!msjError.equals("")) {
            JOptionPane.showMessageDialog(this, msjError,
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoCantidad.requestFocus();
        }

    }//GEN-LAST:event_campoTextoCantidadActionPerformed
  /**
   * Evento que pasa el foco al campo cantidad.
   * @param evt Evento al que escucha
   */
    private void cajaCombinadaVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCombinadaVideojuegosActionPerformed
        campoTextoCantidad.requestFocus();
    }//GEN-LAST:event_cajaCombinadaVideojuegosActionPerformed
    /**
     * Destruye cuadro de dialogo
     * @param evt Evento al que escucha
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed
   /**
    *   MEtodo oyente del boton restaurar que restura los campos de cuadro de dialogo pro default.
    * @param evt Evento al que escucha 
    */
    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        if (operacion == ConstantesGUI.AGREGAR) {
            campoTextoCantidad.setText("");
            cajaCombinadaVideojuegos.setSelectedIndex(0);
        }
    }//GEN-LAST:event_botonRestaurarActionPerformed
  /**
   * Metodo oyente del boton acetar,Valida los campos de entrada, y este establece un nuevo objeto del tipo de videojuegoED.
   * @param evt  Evento al que escucha
   */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        if (validadores.cadenaVacia(campoTextoCantidad.getText())) {
            JOptionPane.showMessageDialog(this, "Cantidad Vacia");
        } else if (!validadores.validaEntero(campoTextoCantidad.getText())) {
            JOptionPane.showMessageDialog(this, "Solo enteros");
        } else if (operacion == ConstantesGUI.AGREGAR) {
            int auxiliar = videojuegoED.getDisponibilidad() + Integer.valueOf(campoTextoCantidad.getText());
            int auxiliar2 = videojuegoED.getExistencia() + Integer.valueOf(campoTextoCantidad.getText());
            videojuegoED.setVideojuego((Videojuego) cajaCombinadaVideojuegos.getSelectedItem());
            videojuegoED.setDisponibilidad(auxiliar);
            videojuegoED.setExistencia(auxiliar2);
            respuesta.delete(0, respuesta.length());
            respuesta.append(ConstantesGUI.ACEPTAR);
            dispose();
        }


    }//GEN-LAST:event_botonAceptarActionPerformed

    private VideojuegoED videojuegoED;
    private DefaultComboBoxModel listaVideojuegos;
    private int operacion;
    private StringBuffer respuesta;
    private Validadores validadores = new Validadores();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JComboBox<String> cajaCombinadaVideojuegos;
    private javax.swing.JTextField campoTextoCantidad;
    private javax.swing.JLabel cantidadActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
