/*
*DlgVideojuego.java
*Creada el 27 de octubre del 2021 17:34 PM
 */
package interfazUsuario;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import objetosNegocio.Videojuego;
import objetosServicio.Fecha;
import validores.Validadores;

/**
 * Cuadro de dialogo para agregar un videojuego, obtener ,etc sobre un
 * archivo.dat. Alumno; Josè Jesùs Orozc Hernàndez ID; 00000229141
 *
 * @author Josè Jesùs Orozco Hernàndez
 */
public class DlgVideojuego extends javax.swing.JDialog {

    /**
     * Creates new form DlgVideojuego
     *
     * @param parent Frame
     * @param title Titulo del dialogo
     * @param modal Modal
     * @param v Videojuego
     * @param operacion Operacion a realizar
     * @param respuesta Respuesta
     */
    public DlgVideojuego(java.awt.Frame parent, String title, boolean modal, Videojuego v, int operacion, StringBuffer respuesta) {
        super(parent, title, modal);
        initComponents();
        this.videojuego = v;
        this.operacion = operacion;
        this.respuesta = respuesta;

        if (operacion == ConstantesGUI.AGREGAR) {
            botonAceptar.setText("Guardar");
        } else if (operacion == ConstantesGUI.DESPLEGAR) {
            botonAceptar.setText("Continuar");
            botonRestaurar.setEnabled(false);
            botonCancelar.setEnabled(false);
        }

        campoTextoNumeroCatalogo.setText(v.getNumCatalogo());
        campoTextoNumeroCatalogo.setEditable(false);
        if ((operacion == ConstantesGUI.DESPLEGAR)) {
            campoTextoTitulo.setText(v.getTitulo());
            campoTextoGenero.setText(v.getGenero());
            campoTextoClasificacion.setText(v.getClasificacion());
            campoTextoConsola.setText(v.getConsola());
            campoTextoFabricante.setText(v.getFabricante());
            campoTextoVersion.setText(v.getVersion());
        }
        if ((operacion == ConstantesGUI.DESPLEGAR)) {
            campoTextoTitulo.setEditable(false);
            campoTextoGenero.setEditable(false);
            campoTextoClasificacion.setEditable(false);
            campoTextoConsola.setEditable(false);
            campoTextoFabricante.setEditable(false);
            campoTextoVersion.setEditable(false);
        }
        respuesta.append(ConstantesGUI.CANCELAR);

        centraCuadroDialogo(parent);

        setVisible(true);
    }

    /**
     * Metodo que centra el cuadro de dialogo
     *
     * @param parent Frame
     */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();

        Dimension dlgSize = getPreferredSize();

        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x,
                (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        botonRestaurar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoTextoNumeroCatalogo = new javax.swing.JTextField();
        campoTextoTitulo = new javax.swing.JTextField();
        campoTextoGenero = new javax.swing.JTextField();
        campoTextoClasificacion = new javax.swing.JTextField();
        campoTextoConsola = new javax.swing.JTextField();
        campoTextoFabricante = new javax.swing.JTextField();
        campoTextoVersion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonRestaurar.setText("Restaurar");
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Numero Catalogo; ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Titulo;");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Genero;");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Clasificacion;");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Consola");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fabricante;");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Version;");

        campoTextoNumeroCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNumeroCatalogoActionPerformed(evt);
            }
        });

        campoTextoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoTituloActionPerformed(evt);
            }
        });

        campoTextoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoGeneroActionPerformed(evt);
            }
        });

        campoTextoClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoClasificacionActionPerformed(evt);
            }
        });

        campoTextoConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoConsolaActionPerformed(evt);
            }
        });

        campoTextoFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoFabricanteActionPerformed(evt);
            }
        });

        campoTextoVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoVersionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(botonCancelar)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTextoNumeroCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(campoTextoTitulo)
                            .addComponent(campoTextoGenero)
                            .addComponent(campoTextoClasificacion)
                            .addComponent(campoTextoConsola)
                            .addComponent(campoTextoFabricante)
                            .addComponent(campoTextoVersion))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoTextoNumeroCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoTextoTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoTextoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoClasificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoTextoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoTextoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTextoVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonRestaurar)
                    .addComponent(botonCancelar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /**
     * Metodo oyente del boton acetar,Valida los campos de entrada, y este
     * establece un nuevo objeto del tipo de videojuego.
     *
     * @param evt Evento al que escucha
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        String msjError = "";
        String titulo = "";
        String genero = "";
        String clasificacion = "";
        String consola = "";
        String fabricante = "";
        String version = "";
        int posError = 0;
        if (operacion == ConstantesGUI.AGREGAR) {
            titulo = campoTextoTitulo.getText();
            genero = campoTextoGenero.getText();
            clasificacion = campoTextoClasificacion.getText();
            consola = campoTextoConsola.getText();
            fabricante = campoTextoFabricante.getText();
            version = campoTextoVersion.getText();

            if (validadores.cadenaVacia(titulo) || !validadores.validaCadena(35, titulo)) {
                msjError = validadores.cadenaVacia(titulo) ? "Titulo Vacio" : "Titulo muy largo";
                posError = 1;
            }
            if (validadores.cadenaVacia(genero) || !validadores.validaCadena(20, genero)) {
                msjError = validadores.cadenaVacia(genero) ? "Faltó el genero" : "Genero muy largo";
                posError = 2;
            }
            if (validadores.cadenaVacia(clasificacion)
                    || !validadores.validaCadena(5, clasificacion)) {
                msjError = validadores.cadenaVacia(clasificacion) ? "Clasificacion vacia" : "Clasificacion muy larga";
                posError = 3;
            }
            if (validadores.cadenaVacia(consola)
                    || !validadores.validaCadena(20, consola)) {
                msjError = validadores.cadenaVacia(consola) ? "Consola vacia" : "Consola muy larga";
                posError = 4;
            }
            if (validadores.cadenaVacia(fabricante)
                    || !validadores.validaCadena(20, fabricante)) {
                msjError = validadores.cadenaVacia(fabricante) ? "Fabricante vacio" : "Fabricante muy largo";
                posError = 5;
            }
            if (validadores.cadenaVacia(version)
                    || !validadores.validaEnteroMaxDigitos(1, version)) {
                msjError = validadores.cadenaVacia(version) ? "Version vacia" : "Version invalida solo un digito.";
                posError = 6;
            }
            if (posError > 0) {
                JOptionPane.showMessageDialog(this, msjError,
                        "Error de entrada.",
                        JOptionPane.ERROR_MESSAGE);
                switch (posError) {
                    case 1:
                        campoTextoTitulo.requestFocus();
                        break;
                    case 2:
                        campoTextoGenero.requestFocus();
                        break;
                    case 3:
                        campoTextoClasificacion.requestFocus();
                        break;
                    case 4:
                        campoTextoConsola.requestFocus();
                        break;
                    case 5:
                        campoTextoFabricante.requestFocus();
                        break;
                    case 6:
                        campoTextoVersion.requestFocus();
                        break;
                }

            }
            videojuego.setTitulo(campoTextoTitulo.getText());
            videojuego.setGenero(campoTextoGenero.getText());
            videojuego.setClasificacion(campoTextoClasificacion.getText());
            videojuego.setConsola(campoTextoConsola.getText());
            videojuego.setFabricante(campoTextoFabricante.getText());
            videojuego.setVersion(campoTextoVersion.getText());

        }
        respuesta.delete(0, respuesta.length());
        respuesta.append(ConstantesGUI.ACEPTAR);
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed
    /**
     * Metodo oyente del boton restaurar, que restaura los campos de entrada a default.
     * @param evt Evento al que escucha
     */
    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        // TODO add your handling code here:
        if (operacion == ConstantesGUI.AGREGAR) {
            campoTextoTitulo.setText("");
            campoTextoGenero.setText("");
            campoTextoClasificacion.setText("");
            campoTextoConsola.setText("");
            campoTextoFabricante.setText("");
            campoTextoVersion.setText("");

        }
    }//GEN-LAST:event_botonRestaurarActionPerformed
  /**
   * Metodo oyente del boton cancelar que destruye el cuadro de dialogo
   * @param evt Evento al que escucha
   */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoTextoNumeroCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNumeroCatalogoActionPerformed

    }//GEN-LAST:event_campoTextoNumeroCatalogoActionPerformed
/**
 * Metodo oyente del campo de texto titulo que verifica si el campo de texto cumple con ciertos criterios.
 * @param evt  Evento al que escucha
 */
    private void campoTextoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoTituloActionPerformed
        String titulo = campoTextoTitulo.getText();
        String msjError = "";
        if (validadores.cadenaVacia(titulo)) {
            msjError = "Faltó el título";
        } else if (!validadores.validaCadena(35, titulo)) {
            msjError = "Título muy largo";
        }
        if (!msjError.equals("")) {
            JOptionPane.showMessageDialog(this, msjError,
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoTitulo.requestFocus();
        } else {
            campoTextoGenero.requestFocus();
        }
    }//GEN-LAST:event_campoTextoTituloActionPerformed
/**
 * Metodo oyente del campo de texto genero que verifica si el campo de genero cumple con ciertos criterios.
 * @param evt  Evento al que escucha
 */
    private void campoTextoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoGeneroActionPerformed
        // TODO add your handling code here:
        String genero = campoTextoGenero.getText();
        String msjError = "";
        if (validadores.cadenaVacia(genero)) {
            msjError = "Faltó el genero";
        } else if (!validadores.validaCadena(20, genero)) {
            msjError = "Genero muy largo";
        }
        if (!msjError.equals("")) {
            JOptionPane.showMessageDialog(this, msjError,
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoGenero.requestFocus();
        } else {
            campoTextoClasificacion.requestFocus();
        }
    }//GEN-LAST:event_campoTextoGeneroActionPerformed
/**
 * Metodo oyente del campo de texto clasificacion, verifica si el campo de clasificacion cumple con ciertos criterios.
 * @param evt  Evento al que escucha
 */
    private void campoTextoClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoClasificacionActionPerformed
        // TODO add your handling code here:
        String clasificacion = campoTextoClasificacion.getText();
        String msjError = "";
        if (validadores.cadenaVacia(clasificacion)) {
            msjError = "Faltó la clasificacion";
        } else if (!validadores.validaCadena(5, clasificacion)) {
            msjError = "Clasificacion muy larga";
        }
        if (!msjError.equals("")) {
            JOptionPane.showMessageDialog(this, msjError,
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoClasificacion.requestFocus();
        } else {
            campoTextoConsola.requestFocus();
        }
    }//GEN-LAST:event_campoTextoClasificacionActionPerformed
/**
 * Metodo oyente del campo de texto consola, verifica si el campo de consola cumple con ciertos criterios.
 * @param evt  Evento al que escucha
 */
    private void campoTextoConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoConsolaActionPerformed
        // TODO add your handling code here:
        String consola = campoTextoConsola.getText();
        String msjError = "";
        if (validadores.cadenaVacia(consola)) {
            msjError = "Faltó la Consola";
        } else if (!validadores.validaCadena(20, consola)) {
            msjError = "Consola muy larga";
        }
        if (!msjError.equals("")) {
            JOptionPane.showMessageDialog(this, msjError,
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoConsola.requestFocus();
        } else {
            campoTextoFabricante.requestFocus();
        }
    }//GEN-LAST:event_campoTextoConsolaActionPerformed
/**
 * Metodo oyente del campo de texto fabricante, verifica si el campo de fabricante cumple con ciertos criterios.
 * @param evt  Evento al que escucha
 */
    private void campoTextoFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoFabricanteActionPerformed
        // TODO add your handling code here:
        String fabricante = campoTextoFabricante.getText();
        String msjError = "";

        if (validadores.cadenaVacia(fabricante)) {
            msjError = "Faltó el fabricante";
        } else if (!validadores.validaCadena(20, fabricante)) {
            msjError = "Fabricante muy largo";
        }
        if (!msjError.equals("")) {
            JOptionPane.showMessageDialog(this, msjError,
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoFabricante.requestFocus();
        } else {
            campoTextoVersion.requestFocus();
        }
    }//GEN-LAST:event_campoTextoFabricanteActionPerformed
/**
 * Metodo oyente del campo de texto version, verifica si el campo de version cumple con ciertos criterios.
 * @param evt  Evento al que escucha
 */
    private void campoTextoVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoVersionActionPerformed
        // TODO add your handling code here:
        String version = campoTextoVersion.getText();

        if (!validadores.cadenaVacia(version) && !validadores.validaEnteroMaxDigitos(1, version)) {
            JOptionPane.showMessageDialog(this, validadores.cadenaVacia(version) == true
                    ? "Version vacia" : "La version no debe de contener letras y solo un digito",
                    "Error de entrada.",
                    JOptionPane.ERROR_MESSAGE);
            campoTextoVersion.requestFocus();
        }
    }//GEN-LAST:event_campoTextoVersionActionPerformed

    private Videojuego videojuego;
    private int operacion;
    private StringBuffer respuesta;
    private Validadores validadores = new Validadores();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JTextField campoTextoClasificacion;
    private javax.swing.JTextField campoTextoConsola;
    private javax.swing.JTextField campoTextoFabricante;
    private javax.swing.JTextField campoTextoGenero;
    private javax.swing.JTextField campoTextoNumeroCatalogo;
    private javax.swing.JTextField campoTextoTitulo;
    private javax.swing.JTextField campoTextoVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
