/*
 * FrmVideocentro.java
 * Creada el 2 de noviembre del 2021 a las 16:24 PM
 */
package interfazUsuario;

import control.Control;
import control.Tabla;
import excepciones.PersistenciaException;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * FrmVideocentro donde se prueba el videocentro.
 *
 * @author josej
 */
public class FrmVideocentro extends javax.swing.JFrame {

    Control control = new Control();

    /**
     * Creates new form FrmVideocentro
     */
    public FrmVideocentro() {
        initComponents();
        centraVentana();
    }

    /**
     * Este método centra la ventana de la aplicación sobre la pantalla
     */
    private void centraVentana() {
        //Obtiene el tamaño de la pantalla 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtiene el tamaño de la ventana de la aplicación 
        Dimension frameSize = getSize();

        // Se asegura que el tamaño de la ventana de la aplicación 
        // no exceda el tamaño de la pantalla 
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        // Centra la ventana de la aplicación sobre la pantalla 
        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * Este método crea un objeto del tipo JTable dentro de un panel con barras
     * de deslizamiento y la despliega
     *
     * @param tabla objeto TableModel con los datos de una tabla
     */
    public void despliegaTabla(Tabla tabla) {
        // Crea la tabla a partir del modelo de la tabla con los valores 
        // de los titulos de las columnas y los valores de las celdas 
        jtabla = new javax.swing.JTable(tabla.getModeloTabla());
        // Establece el título de la tabla 
        tituloTabla.setText(tabla.getTitulo());
        // Hace que el control del tamaño de la tabla y la porción visible 
        // lo tenga la barra de deslizamiento y no la tabla 
        jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtabla.setAutoscrolls(false);
        // Hace visible la tabla dentro del panel con barras de 
        // deslizamiento 
        jScrollPane1.setViewportView(jtabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tituloTabla = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCatalogos = new javax.swing.JMenu();
        menuCatalogoVideojuegos = new javax.swing.JMenu();
        opcionMenuAgregarVideojuego = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcionMenuSalir = new javax.swing.JMenuItem();
        menuInventarios = new javax.swing.JMenu();
        menuInventariosVideojuegos = new javax.swing.JMenu();
        opcionMenuInventariarVideojuego = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultaVideojuegos = new javax.swing.JMenu();
        menuConsultaInventarioVideojuegos = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        opcionMenuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Videocentro");

        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tituloTabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menuCatalogos.setText("Catalogos");

        menuCatalogoVideojuegos.setText("Videojuegos");

        opcionMenuAgregarVideojuego.setText("Agregar");
        opcionMenuAgregarVideojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarVideojuegoActionPerformed(evt);
            }
        });
        menuCatalogoVideojuegos.add(opcionMenuAgregarVideojuego);

        menuCatalogos.add(menuCatalogoVideojuegos);
        menuCatalogos.add(jSeparator1);

        opcionMenuSalir.setText("Salir");
        menuCatalogos.add(opcionMenuSalir);

        jMenuBar1.add(menuCatalogos);

        menuInventarios.setText("Inventarios");

        menuInventariosVideojuegos.setText("Inventarios");

        opcionMenuInventariarVideojuego.setText("Inventariar");
        opcionMenuInventariarVideojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuInventariarVideojuegoActionPerformed(evt);
            }
        });
        menuInventariosVideojuegos.add(opcionMenuInventariarVideojuego);

        menuInventarios.add(menuInventariosVideojuegos);

        jMenuBar1.add(menuInventarios);

        menuConsultas.setText("Consultas");

        menuConsultaVideojuegos.setText("Videojuegos");
        menuConsultas.add(menuConsultaVideojuegos);

        menuConsultaInventarioVideojuegos.setText("Inventario Videojuegos");
        menuConsultas.add(menuConsultaInventarioVideojuegos);

        jMenuBar1.add(menuConsultas);

        menuAyuda.setText("Ayuda");

        opcionMenuAcercaDe.setText("Acerca de");
        opcionMenuAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcionMenuAcercaDeMouseEntered(evt);
            }
        });
        menuAyuda.add(opcionMenuAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
   * Metodo oyente del la opcion menu agregar que manda a llamar al metodo agregar de la clase control.
   * @param evt Evento el que escucha
   */
    private void opcionMenuAgregarVideojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarVideojuegoActionPerformed
        // TODO add your handling code here:
        try {
            control.agregaVideojuego(this);
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        Tabla tablaVideojuegos = control.getTablaVideojuegos(this);
        if (tablaVideojuegos != null) {
            despliegaTabla(tablaVideojuegos);
        }
    }//GEN-LAST:event_opcionMenuAgregarVideojuegoActionPerformed
  /**
   * Metodo oyente del la opcion menu inventariar que manda a llamar al metodo inventariar de la clase control.
   * @param evt Evento el que escucha
   */
    private void opcionMenuInventariarVideojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuInventariarVideojuegoActionPerformed
        // TODO add your handling code here:
        try {
            control.inventariarVideojuego(this);
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        Tabla tablaVideojuegosED = control.getTablaVideojuegosED(this);
        if (tablaVideojuegosED != null) {
            despliegaTabla(tablaVideojuegosED);
        }
    }//GEN-LAST:event_opcionMenuInventariarVideojuegoActionPerformed
  /**
   * Metodo oyente del la opcion menu acerca de que establece un TootlTipText, con mis datos.
   * @param evt Evento el que escucha
   */
    private void opcionMenuAcercaDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionMenuAcercaDeMouseEntered
        // TODO add your handling code here:
        opcionMenuAcercaDe.setToolTipText(
                "" + "<html>"
                + "<head>"
                + ""
                + "</head>"
                + "<body>"
                + "Semestre agosto-diciembre 2021<br>Clase de programacion Maestra Karina<br>ID; 00000229141  José Jesús Orozco Hernández "
                + "</body>"
                + "</html>"
                + "");
    }//GEN-LAST:event_opcionMenuAcercaDeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVideocentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVideocentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVideocentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVideocentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmVideocentro dialog = new FrmVideocentro();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCatalogoVideojuegos;
    private javax.swing.JMenu menuCatalogos;
    private javax.swing.JMenu menuConsultaInventarioVideojuegos;
    private javax.swing.JMenu menuConsultaVideojuegos;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuInventarios;
    private javax.swing.JMenu menuInventariosVideojuegos;
    private javax.swing.JMenuItem opcionMenuAcercaDe;
    private javax.swing.JMenuItem opcionMenuAgregarVideojuego;
    private javax.swing.JMenuItem opcionMenuInventariarVideojuego;
    private javax.swing.JMenuItem opcionMenuSalir;
    private javax.swing.JLabel tituloTabla;
    // End of variables declaration//GEN-END:variables
private javax.swing.JTable jtabla;

}
