/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;
import java.awt.Dimension;
import java.awt.Point;
import objetosNegocio.Usuario;
/**
 *
 * @author jvale
 */
public class DlgUsuario extends javax.swing.JDialog {

    /**
     * Creates new form DlgUsuario
     */
    public DlgUsuario(java.awt.Frame parent,String title, boolean modal,Usuario usuario,int operacion,StringBuffer respuesta) {
        super(parent, modal);
        initComponents();
        this.usuario=usuario;
        this.operacion=operacion;
        this.respuesta=respuesta;
        centraCuadroDialogo(parent);
        // Modifica el título del botón botonAceptar y establece si los 
        // botones botonRestaurar y botonCancelar estarán habilitados. 
        // Si la operación es agregar 
        if(operacion == ConstantesGUI.AGREGAR) 
        botonAceptar.setText("Aceptar"); 
        // Si la operación es actualizar 
        else if(operacion == ConstantesGUI.ACTUALIZAR) 
        botonAceptar.setText("Actualizar"); 
        // Si la operación es eliminar 
        else if(operacion == ConstantesGUI.ELIMINAR) { 
        botonAceptar.setText("Eliminar"); 
        botonRestaurar.setEnabled(false); 
        } 
        // Si la operación es desplegar 
        else if(operacion == ConstantesGUI.DESPLEGAR) { 
        botonAceptar.setText("Continuar"); 
        botonRestaurar.setEnabled(false); 
        botonCancelar.setEnabled(false); 
        }
        // Despliega el numero de credencial del usuario 
        campoTextoNumCredencial.setText(usuario.getNumCredencial()); 
        // Si la operación es de actualizar, eliminar o desplegar, 
        if((operacion == ConstantesGUI.ELIMINAR) || 
        (operacion == ConstantesGUI.ACTUALIZAR) || 
        (operacion == ConstantesGUI.DESPLEGAR)) { 
        // despliega el resto de los datos del usuario 
        campoTextoNombre.setText(usuario.getNombre());
        campoTextoDireccion.setText(usuario.getDireccion());
        campoTextoTelefono.setText(usuario.getTelefono());
        campoTextoMulta.setText(String.valueOf(usuario.getMulta()));
        // Si la operación es de eliminar o desplegar 
        if((operacion == ConstantesGUI.ELIMINAR) || 
        (operacion == ConstantesGUI.DESPLEGAR)) { 
        // hace los campos de texto de sólo lectura 
        campoTextoNombre.setEditable(false); 
        campoTextoDireccion.setEditable(false); 
        campoTextoTelefono.setEditable(false); 
        campoTextoMulta.setEditable(false);
        }
        // Establece el valor por omisión para respuesta, por si se cierra el 
        // cuadro de diálogo presionando el botón cerrar o el botón cancelar 
        respuesta.append(ConstantesGUI.CANCELAR); 
        // centra el cuadro de dialogo sobre la ventana de la aplicación 
         

        // Muestra el cuadro de diálogo 
       
    }
         setVisible(true);
    }
        /** 
        * Este método centra el cuadro de dialogo sobre la ventana de la 
        * aplicación. 
        * @param parent Ventana sobre la que aparecerá el cuadro de diálogo 
        */ 
        private void centraCuadroDialogo(java.awt.Frame parent) { 
        // Obtiene el tamaño y posición de la ventana de la aplicación 
        Dimension frameSize = parent.getSize(); 
        Point loc = parent.getLocation(); 
        // Obtiene el tamaño del cuadro de diálogo 
        Dimension dlgSize = getPreferredSize(); 

        // Centra el cuadro de diálogo sobre la ventana padre 
        setLocation( (frameSize.width - dlgSize.width) / 2 + loc.x, 
        (frameSize.height - dlgSize.height) / 2 + loc.y); 
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoDireccion = new javax.swing.JTextField();
        campoTextoTelefono = new javax.swing.JTextField();
        campoTextoNumCredencial = new javax.swing.JTextField();
        campoTextoMulta = new javax.swing.JTextField();
        botonRestaurar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Captura de datos usuario");

        jLabel1.setText("Nombre");

        jLabel2.setText("Dirección");

        jLabel3.setText("Teléfono");

        jLabel4.setText("Num. Credencial");

        jLabel5.setText("Multa");

        campoTextoNombre.setColumns(10);
        campoTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNombreActionPerformed(evt);
            }
        });

        campoTextoDireccion.setColumns(10);

        campoTextoTelefono.setColumns(10);

        campoTextoNumCredencial.setEditable(false);
        campoTextoNumCredencial.setColumns(10);

        campoTextoMulta.setColumns(10);
        campoTextoMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoMultaActionPerformed(evt);
            }
        });

        botonRestaurar.setText("Restaurar");
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoNumCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(botonRestaurar)
                        .addGap(70, 70, 70)
                        .addComponent(botonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNumCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoTextoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonRestaurar)
                    .addComponent(botonCancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNombreActionPerformed

    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        if(operacion == ConstantesGUI.AGREGAR) {
        campoTextoNombre.setText("");
        campoTextoDireccion.setText("");
        campoTextoTelefono.setText("");
        campoTextoMulta.setText("");
        }

        // Si la operación es Actualizar
        if(operacion == ConstantesGUI.ACTUALIZAR) {
        campoTextoNombre.setText(usuario.getNombre());
        campoTextoDireccion.setText(usuario.getDireccion());
        campoTextoTelefono.setText(usuario.getTelefono());
        String multa= String.valueOf(usuario.getMulta());
        campoTextoMulta.setText(multa);
 

 }
    }//GEN-LAST:event_botonRestaurarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if((operacion == ConstantesGUI.AGREGAR) ||
        (operacion == ConstantesGUI.ACTUALIZAR)) 
        {
        // Toma los valores capturados en los campos de texto y en la caja
        // combinada y almacénalos en el parámetro usuario
        usuario.setNombre(campoTextoNombre.getText());
        usuario.setDireccion(campoTextoDireccion.getText());
        usuario.setTelefono(campoTextoTelefono.getText());
        usuario.setMulta(usuario.getMulta());
        }
        // Borra el contenido de respuesta
        respuesta.delete(0, respuesta.length());
        // Establece que se presionó el botón botonAceptar
        respuesta.append(ConstantesGUI.ACEPTAR);
        // Destruye el cuadro de díalogo
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
       
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoTextoMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoMultaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JTextField campoTextoDireccion;
    private javax.swing.JTextField campoTextoMulta;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoNumCredencial;
    private javax.swing.JTextField campoTextoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    private Usuario usuario; 
    private int operacion; 
    private StringBuffer respuesta;
}
